package core;

public enum PatientState {
	
	WAITING_REGISTRATION("WAITING_REGISTRATION"),
	WAITING_INSTALLATION("WAITING_INSTALLATION"),
	WAITING_CONSULTATION("WAITING_CONSULTATION"),
	WAITING_TRANSPORTATION("WAITING_TRANSPORTATION"),
	WAITING_XRAY("WAITING_XRAY"),
	WAITING_BLOOD("WAITING_BLOOD"),
	WAITING_MRI("WAITING_MRI"),
	BEING_INSTALLED("BEING_INSTALLED"),
	BEING_CONSULTED("BEING_CONSULTED"),
	BEING_TRANSPORTED("BEING_TRANSPORTED"),
	BEING_EXAMINATED("BEING_EXAMINATED"),
	WAITING_RELEASE("WAITING_RELEASE"),
	RELEASED("RELEASED");
	
	private String name;
	
	PatientState(String name){
		this.name = name;
	}
	
	public String getName() {
		return this.name;
	}
}
